name: Builddddd
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/build.yml'
      - 'appcast.xml'

jobs:
  build:
    runs-on: ubuntu-latest  # This needs to be changed to an Alpine image
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: alpine-3.14  # Adjust the Alpine version as needed
            aarch: amd64
            targets:
              - binary  # Adjust targets as needed for Alpine
            filename: hiddify-alpine-x64  # Adjust the filename accordingly

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build for Alpine
        run: |
          docker buildx create --name mybuilder --use
          docker buildx build --platform linux/amd64 -t myapp .
      
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: .  # Replace this with the path to your built binary or artifacts
